#!/usr/bin/env php
<?php
/**
 * @author Kirill Saksin <kirillsaksin@yandex.ru>
 */

foreach (['/vendor/autoload.php', '/../autoload.php', '/../../autoload.php', '/../vendor/autoload.php'] as $autoloadFile) {
    if (file_exists(__DIR__ . $autoloadFile)) {
        require_once __DIR__ . $autoloadFile;
        break;
    }
}


(new \Smt\TeamCityIntegration\Application\Application())->run(isset($argv[1]) ? $argv[1] : '/srv');
