#!/usr/bin/env php
<?php
/**
 * @author Kirill Saksin <kirillsaksin@yandex.ru>
 */

require_once __DIR__ . '/vendor/autoload.php';

(new \Smt\TeamCityIntegration\Application\Application())->run(isset($argv[1]) ? $argv[1] : '/srv');
